### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by centralscrutinizer21** [Gredin67/mautrix_signal_ynh#1]
install fails

- Hardware: Raspberry Pi 4 at home 
- YunoHost version: 4.1.7.4
- I have access to my server: Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Trying to install package version/brench: testing
### Steps to reproduce

ssh as admin to server
```
sudo su
    sudo yunohost app install https://github.com/YunoHost-Apps/mautrix_signal_ynh/tree/testing --debug
```

### Logs
https://paste.yunohost.org/raw/borodekale

**Comment by Gredin67** [comment]
The package has not been tested on ARM(HF) architecture.
Obviously at least one of the following dependency is not available. libunixsocket-java, signaldctl, signald
Maybe it can be solved by compiling from source...

Le 2 avril 2021 23:50:32 GMT+02:00, centralscrutinizer21 ***@***.***> a écrit :
>
>
>install fails
>
>- Hardware: Raspberry Pi 4 at home 
>- YunoHost version: 4.1.7.4
>- I have access to my server: Through SSH 
>- Are you in a special context or did you perform some particular
>tweaking on your YunoHost instance?: no 
>- Trying to install package version/brench: testing
>### Steps to reproduce
>
>ssh as admin to server
>sudo su
>sudo yunohost app install
>https://github.com/YunoHost-Apps/mautrix_signal_ynh/tree/testing
>--debug
>
>### Logs
>https://paste.yunohost.org/raw/borodekale
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Gredin67/mautrix_signal_ynh/issues/1

-- Envoyé depuis /e/ Mail.
-- Envoyé depuis /e/ Mail.

**Comment by Gredin67** [comment]
See here https://gitlab.com/signald/signald/-/issues/130
Until this issue is solved, signald should be compiled from source https://signald.org/articles/install/source/

Le 2 avril 2021 23:50:32 GMT+02:00, centralscrutinizer21 ***@***.***> a écrit :
>
>
>install fails
>
>- Hardware: Raspberry Pi 4 at home 
>- YunoHost version: 4.1.7.4
>- I have access to my server: Through SSH 
>- Are you in a special context or did you perform some particular
>tweaking on your YunoHost instance?: no 
>- Trying to install package version/brench: testing
>### Steps to reproduce
>
>ssh as admin to server
>sudo su
>sudo yunohost app install
>https://github.com/YunoHost-Apps/mautrix_signal_ynh/tree/testing
>--debug
>
>### Logs
>https://paste.yunohost.org/raw/borodekale
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Gredin67/mautrix_signal_ynh/issues/1

-- Envoyé depuis /e/ Mail.
-- Envoyé depuis /e/ Mail.

**Comment by centralscrutinizer21** [comment]
Hello, I managed to compile signald and signaldctl but the installation still gives me the same error. I guess the package need to be compiled and installed in a specific location in order for the install script to find them. I'm sorry I have very basic knowledge.
Can you point me to some documentation?

**Comment by gautz** [comment]
I don't have more knowledge about it sorry. You may ask the maintainer to support ARM.

**Comment by centralscrutinizer21** [comment]
I just wrote him about it and he suggested to pass `--no-recommends` to the install command "to skip installing the recommended package signaldctl. It's not required, just a utility to make interacting with signald easier, so skipping that shouldnt be an issue" quoting from him... Is it possible or signaldtc is necessary for your package to work?

**Comment by centralscrutinizer21** [comment]
Here is the conversation https://gitlab.com/signald/signald/-/issues/130
Maybe you can understand each other better than I do :)

**Comment by Gredin67** [comment]
I tried to remove the signalctl dependency, you can try again the testing branch

**Comment by centralscrutinizer21** [comment]
Thanks still failing but I think for a syntax error:
https://paste.yunohost.org/raw/casolufafa

**Comment by Gredin67** [comment]
I removed the dependency to signalctl but I did not find an option to do ``--no-install-recommends`` 
 https://github.com/Yunohost-apps/mautrix_signal_ynh/blob/testing/scripts/install#L112
Might work, I also updated to 0.1.1

**Comment by centralscrutinizer21** [comment]
Install  succeeded but i got errors int he bot room with command link and register :(
here is the installation log:
https://paste.yunohost.org/raw/basohofoji

**Comment by centralscrutinizer21** [comment]
> I removed the dependency to signalctl but I did not find an option to do `--no-install-recommends`
> https://github.com/Yunohost-apps/mautrix_signal_ynh/blob/testing/scripts/install#L112
> Might work, I also updated to 0.1.1

anyway I am no expert but wasn't it `install --no-recommends` ?

**Comment by linkinparkrulz** [comment]
Hardware: Yunohost VM 
YunoHost version: 4.1.7.4
I have access to my server: Terminal and GUI
Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
Trying to install package version/brench: production

Install Warning:

Failed building wheel for mautrix_signal

When I try and start the service after install I get this:

mautrix.errors.base.MatrixConnectionError: Cannot connect to host btcmb.org:443 ssl:default [Connect call failed ('IP address', 443)]
[2021-04-15 16:34:58,053] [INFO@mau.init] Initializing mautrix-signal 0.1.0+dev.unknown
[2021-04-15 16:34:58,060] [INFO@mau.init] Initialization complete in 0.31 seconds
[2021-04-15 16:34:58,061] [DEBUG@mau.init] Running startup actions...
[2021-04-15 16:34:58,062] [DEBUG@mau.db] Connecting to postgres://mautrix_signal:key@localhost:5432/mautrix_signal
[2021-04-15 16:34:58,126] [DEBUG@mau.init] Starting appservice...
[2021-04-15 16:34:58,127] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:8449
[2021-04-15 16:34:58,129] [INFO@mau.mx] Ensuring connectivity to homeserver

If I can get this going I would love to help with the README

**Comment by Gredin67** [comment]
Did you install the synapse app beforehand? Did you install the master or testing branch?

Le 16 avril 2021 15:10:15 GMT+02:00, Linkinparkrulz ***@***.***> a écrit :
>Hardware: Yunohost VM 
>YunoHost version: 4.1.7.4
>I have access to my server: Terminal and GUI
>Are you in a special context or did you perform some particular
>tweaking on your YunoHost instance?: no
>Trying to install package version/brench: production
>
>Install Warning:
>
>Failed building wheel for mautrix_signal
>
>When I try and start the service after install I get this:
>
>mautrix.errors.base.MatrixConnectionError: Cannot connect to host
>btcmb.org:443 ssl:default [Connect call failed ('IP address', 443)]
>[2021-04-15 16:34:58,053] ***@***.*** Initializing mautrix-signal
>0.1.0+dev.unknown
>[2021-04-15 16:34:58,060] ***@***.*** Initialization complete in
>0.31 seconds
>[2021-04-15 16:34:58,061] ***@***.*** Running startup actions...
>[2021-04-15 16:34:58,062] ***@***.*** Connecting to
***@***.***:5432/mautrix_signal
>[2021-04-15 16:34:58,126] ***@***.*** Starting appservice...
>[2021-04-15 16:34:58,127] ***@***.*** Starting appservice web server
>on 0.0.0.0:8449
>[2021-04-15 16:34:58,129] ***@***.*** Ensuring connectivity to
>homeserver
>
>If I can get this going I would love to help with the README
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Gredin67/mautrix_signal_ynh/issues/1#issuecomment-821162685

-- Envoyé depuis /e/ Mail.

**Comment by linkinparkrulz** [comment]
i installed the synapse app through the terminal and I think it was the master.

yunohost app install matrix-synapse I believe

**Comment by Gredin67** [comment]
Did you change the config file? Did you restart the synapse and mautrix_signal services? Can you send the full log of the service start using yunopaste? Maybe also something like
``sudo tail -f -n 500 /var/log/matrix-synapse/homeserver.log | grep signal``
-- Envoyé depuis /e/ Mail.

**Comment by linkinparkrulz** [comment]
Gredin67 I was able to get it up and running with some help from someone @ #mautrix-signal:maunium.net.

It ended up being a problem with my /etc/hosts file. I've included my exchange with redacted names and IPs for people that experience the same thing. I am sure it is probably my doing, but for less experienced users that have a fully operating matrix-synapse server and don't understand why it's not connecting with mautrix-signal I think this will help. 

One other thing that I had done prior to this exchange was find the registration.yaml file, but it was not labelled as such. It was titled mautrix-signal.yaml. I found it randomly in my CLI travels. It also was not linked in the homeserver.yaml file of matrix-synapse. I am not sure if doing that prior to my conversation had any effect, but just thought I would include that.

[issue.txt](https://github.com/Gredin67/mautrix_signal_ynh/files/6329220/issue.txt)

**Comment by centralscrutinizer21** [comment]
Hello Gredin67 I am still trying to make this work, but I didn't find linkinprkrulz suggestion helpful in my case..
I attach here the installation log: https://paste.yunohost.org/raw/enawucimiq
and the mautrix_signal.log: https://paste.yunohost.org/famucuqore.sql
If i can help you help me somehow please let me know
Thanks

**Comment by Gredin67** [comment]
@centralscrutinizer21 did you add your matrix server to the list of authorized users in the config.yaml ? Did you check the signald logs to understand what happens when you try to link ?

**Comment by centralscrutinizer21** [comment]
@Gredin67 I have this settings in config.yaml:
```
# Permissions for using the bridge.
    # Permitted values:
    #       user - Use the bridge with puppeting.
    #      admin - Use and administrate the bridge.
    # Permitted keys:
    #        * - All Matrix users
    #   domain - All users on that homeserver
    #     mxid - Specific user
    permissions:
        n*******ia.nohost.me: user
        '@ce*********zer:n************ia.nohost.me': admin
```
And this is what signald log has to say:
```
May 10 01:00:48 n**********ia.nohost.me signald[747]: 01:00:48.243 [socketlistener] INFO  io.finn.signald.SocketHandler - Client connected
May 15 22:24:52 n**********ia.nohost.me signald[747]: 22:24:52.451 [socketlistener] ERROR finish_link - error while handling request
May 15 22:24:52 n**********ia.nohost.me signald[747]: org.asamk.signal.UserAlreadyExists: null
```

**Comment by Gredin67** [comment]
please post a new issue here https://github.com/YunoHost-Apps/mautrix_signal_ynh
if remaining
